# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-01-03 16:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CakeModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name='Название')),
                ('description', models.CharField(max_length=40, verbose_name='Описание')),
                ('weight', models.FloatField(verbose_name='Вес')),
                ('macrobiotic_value', models.FloatField(verbose_name='Энергитическая ценность')),
                ('cost', models.FloatField(verbose_name='Стоимость')),
                ('image', models.FileField(upload_to='cakes', verbose_name='Изображение')),
            ],
            options={
                'verbose_name': 'Торт',
                'verbose_name_plural': 'Торты',
            },
        ),
    ]
