# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-01-05 15:37
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('photogallery', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedbackModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name='Имя')),
                ('e_mail', models.EmailField(blank=True, max_length=254)),
                ('phone_number', models.IntegerField(validators=[django.core.validators.RegexValidator('[0-9]{10}', 'Incorrectly phone number')])),
                ('message', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='ReviewModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name='Имя')),
                ('review', models.CharField(max_length=100, verbose_name='Отзыв')),
                ('rating', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)], verbose_name='Оценка')),
                ('cake', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='photogallery.CakeModel', verbose_name='Торт')),
            ],
            options={
                'verbose_name': 'Отзыв',
                'verbose_name_plural': 'Отзывы',
            },
        ),
    ]
