# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-02-10 09:45
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photogallery', '0002_feedbackmodel_reviewmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cakemodel',
            name='image',
            field=models.ImageField(height_field=100, upload_to='cakes', verbose_name='Изображение', width_field=100),
        ),
        migrations.AlterField(
            model_name='feedbackmodel',
            name='message',
            field=models.CharField(max_length=200, verbose_name='Сообщение'),
        ),
        migrations.AlterField(
            model_name='feedbackmodel',
            name='phone_number',
            field=models.IntegerField(validators=[django.core.validators.RegexValidator('[0-9]{10}', 'Incorrectly phone number')], verbose_name='Телефонный номер'),
        ),
    ]
